name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  # 1. Test and Security Job
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install -r requirements.txt pytest bandit
      - name: Run Unit Tests
        run: pytest
      - name: Run Security Scan (Bandit)
        run: bandit -r app/
